services:
  - type: web
    name: notes-app-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notes-app-db
          property: connectionString

databases:
  - name: notes-app-db
    plan: free
    databaseName: notes_app
    user: notes_user